// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARGAKplkuf6FFwNsCg96l21cy0TSBlxYE',
    appId: '1:344507006010:web:5fddcc0543e136bf260903',
    messagingSenderId: '344507006010',
    projectId: 'megafood-409814',
    authDomain: 'megafood-409814.firebaseapp.com',
    storageBucket: 'megafood-409814.appspot.com',
    measurementId: 'G-P3R4PY6NE0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlc_P8oOCpOvxTAKkvijD65nVcVTGI2Xg',
    appId: '1:344507006010:android:872f18f7d0aa3484260903',
    messagingSenderId: '344507006010',
    projectId: 'megafood-409814',
    storageBucket: 'megafood-409814.appspot.com',
  );
}
